language: node_js

node_js:
    - '12'

before_install:
    - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
    - sudo apt-get -y install libxml2-dev
    - sudo apt-get -y install rsync

addons:
    apt:
        update: true
    ssh_known_hosts:
        - dev.eportfolio.tech
        - haswf.com
        - 103.108.228.162

install:
    - rm -rf node_modules
    - rm -f package-lock.json
    - npm install
    - npm ci

# keep the npm cache around to speed up installs
cache:
    directories:
        - '$HOME/.npm'

script:
    - npm test
    - if [ $TRAVIS_BRANCH == "master" ]; then
      CI=false npm run build-prod;
      else
      CI=false npm run build;
      fi

before_deploy:
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    - ssh -i ./deploy_key haswell@haswf.com pwd

deploy:
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet -e 'ssh' $TRAVIS_BUILD_DIR/build/* haswell@haswf.com:/home/haswell/prod/
      on:
          branch: master
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet -e 'ssh' $TRAVIS_BUILD_DIR/build/* haswell@haswf.com:/home/haswell/dev/
      on:
          branch: dev

after_deploy:
    - rm -f /home/haswell/COMP30022FrontEndDev/deploy_key

notifications:
    slack: comp30022-workspace:7vMQ7aLMccsS6rzFGygUEaTG
